### ISSUE TITLE
How to show y-axis on the right side of chart?

### ISSUE THREAD

**Issue by isaranjha** [AAChartModel/AAChartKit-Swift#317] opened 2021-07-20 11:14 UTC
How can I show the y-axis on the right side of the chart?

**Comment by geekstars** [comment] 2021-07-23 06:50
Hope to help you

let aaOptions = aaChartModel.aa_toAAOptions()
aaOptions.yAxis?.opposite(true)

aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by geekstars** [comment] 2021-07-23 06:57
Duplicate of #95

**Closed** 2021-07-23 09:45 UTC
Labels: duplicate
