### ISSUE TITLE
How to display yAxis at right side?

### ISSUE THREAD

**Issue by iOS-dev-avinash** [AAChartModel/AAChartKit-Swift#98] opened 2018-11-02 04:13 UTC
How to display yAxis at right side?

**Comment by geekstars** [comment] 2021-07-23 06:52
Hope to help you @iOS-dev-avinash 

let aaOptions = aaChartModel.aa_toAAOptions()
aaOptions.yAxis?.opposite(true)

aaChartView.aa_drawChartWithChartOptions(aaOptions)

**Comment by geekstars** [comment] 2021-07-23 06:57
Duplicate of #95

**Closed** 2021-07-23 09:49 UTC
Labels: duplicate
